kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: summit-instructlab-demo-2024
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'summit-instructlab-demo-2024:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.webapp
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/HunterGerlach/summit-instructlab-demo-2024'
  runPolicy: Serial
