kind: Deployment
apiVersion: apps/v1
metadata:
  name: summit-instructlab-demo-2024
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: summit-instructlab-demo-2024
  template:
    metadata:
      labels:
        deployment: summit-instructlab-demo-2024
    spec:
      containers:
        - name: summit-instructlab-demo-2024
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo-summit/summit-instructlab-demo-2024:latest
          ports:
            - containerPort: 8501
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: vectordb-config
              mountPath: /app/config.yaml
              subPath: config.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
        - name: vectordb-config
          configMap:
            name: vectordb-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
